spring.application.name=BridgeServer
spring.data.mongodb.uri=mongodb+srv://aniruddhabiswas105_db_user:69pK6xIRZNE5RRvX@cluster0.pghexzp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=bridge
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.authentication-database=admin





